import type { Metadata } from "next";
import "./globals.css";
import { Barlow } from 'next/font/google';

const barlow = Barlow({
  weight: ['400','600', '700'], // Specify the weights you need
  subsets: ['latin'],
  variable: '--font-barlow',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${barlow.variable} font-sans antialiased`}>
        {children}
      </body>
    </html>
  );
}
